const test=require('node:test');const assert=require('node:assert/strict');
const {launchBrowser}=require('../automation/launch');const {advance}=require('../automation/issuer-engine');
test('issuer engine fills CE, waits for human CAPTCHA and submits once',async()=>{
 const browser=await launchBrowser(true);try{
 const context=await browser.newContext();await context.route('https://consultapublica.sefaz.ce.gov.br/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:`<label><input id="cnpj" type="radio" name="tipoDevedor">CNPJ</label><input id="codigoDevedor"><input id="captcha"><button onclick="window.submissions=(window.submissions||0)+1">Pesquisar</button>`}));
 const page=await context.newPage();await page.goto('https://consultapublica.sefaz.ce.gov.br/form');
 const job={mode:'issue',status:'awaiting_user',cnpj:'00000000000191',context,portal:{key:'estadual',allowedHosts:['consultapublica.sefaz.ce.gov.br']}};
 assert.equal((await advance(job)).status,'captcha_required');assert.equal(await page.locator('#codigoDevedor').inputValue(),job.cnpj);assert.equal(await page.locator('#cnpj').isChecked(),true);assert.equal(await page.evaluate(()=>window.submissions||0),0);
 await page.locator('#captcha').fill('human-test');assert.equal((await advance(job)).status,'awaiting_response');await advance(job);assert.equal(await page.evaluate(()=>window.submissions),1);
 }finally{await browser.close();}
});
test('federal emission is automatic and never clicks query after emission',async()=>{
 const browser=await launchBrowser(true);try{const context=await browser.newContext();await context.route('https://servicos.receitafederal.gov.br/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:`<input name="niContribuinte"><button onclick="window.issued=(window.issued||0)+1">Emitir Certidão</button><button onclick="window.queried=true">Consultar Certidão</button>`}));const page=await context.newPage();await page.goto('https://servicos.receitafederal.gov.br/form');const job={mode:'issue',status:'awaiting_user',cnpj:'00000000000191',context,portal:{allowedHosts:['servicos.receitafederal.gov.br']}};await advance(job);await advance(job);assert.equal(await page.locator('input').inputValue(),job.cnpj);assert.equal(await page.evaluate(()=>window.issued),1);assert.equal(await page.evaluate(()=>Boolean(window.queried)),false);}finally{await browser.close();}
});
test('untrusted page and verification mode cannot trigger issuance',async()=>{
 const browser=await launchBrowser(true);try{const context=await browser.newContext();await context.route('https://example.com/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:'<input name="cnpj"><button onclick="window.sent=true">Emitir</button>'}));const page=await context.newPage();await page.goto('https://example.com/form');const job={mode:'issue',status:'awaiting_user',cnpj:'00000000000191',context,portal:{allowedHosts:['www.tst.jus.br']}};assert.equal((await advance(job)).status,'awaiting_user');assert.equal(await page.locator('input').inputValue(),'');job.mode='verify';job.portal.allowedHosts=['example.com'];await advance(job);assert.equal(await page.evaluate(()=>Boolean(window.sent)),false);}finally{await browser.close();}
});
test('Fortaleza selects municipal scope and legal entity before filling; TST opens its form',async()=>{
 const browser=await launchBrowser(true);try{
 const context=await browser.newContext();const host='grpfordam.sefin.fortaleza.ce.gov.br';
 await context.route(`https://${host}/**`,r=>r.fulfill({contentType:'text/html; charset=utf-8',body:`<select id="tipoCertidao"><option>Selecione...</option><option>Certidão Negativa de Débitos de Tributos Municipais</option></select><label><input type="radio" name="pessoa" onchange="document.querySelector('#cnpj').hidden=false">Jurídica</label><input id="cnpj" hidden><input id="captcha"><input type="button" value="Emitir" onclick="window.sent=true">`}));
 const page=await context.newPage();await page.goto(`https://${host}/form`);const job={mode:'issue',status:'awaiting_user',cnpj:'00000000000191',context,portal:{allowedHosts:[host]}};
 await advance(job);await advance(job);assert.equal((await advance(job)).status,'captcha_required');assert.equal(await page.locator('#cnpj').inputValue(),job.cnpj);assert.equal(await page.evaluate(()=>Boolean(window.sent)),false);await context.close();
 const ctx=await browser.newContext();await ctx.route('https://cndt-certidao.tst.jus.br/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:r.request().url().endsWith('/gerarCertidao')?'<input id="cpfCnpj"><input id="captcha-resposta"><input type="submit" value="Emitir Certidão">':'<a href="/gerarCertidao">Emitir Certidão</a>'}));const tst=await ctx.newPage();await tst.goto('https://cndt-certidao.tst.jus.br/');const task={mode:'issue',status:'awaiting_user',cnpj:job.cnpj,context:ctx,portal:{allowedHosts:['cndt-certidao.tst.jus.br']}};await advance(task);assert.equal((await advance(task)).status,'captcha_required');assert.equal(await tst.locator('#cpfCnpj').inputValue(),job.cnpj);
 }finally{await browser.close();}
});
test('masked controls receive keyboard events and official failures are reported',async()=>{
 const browser=await launchBrowser(true);try{const context=await browser.newContext();await context.route('https://servicos.receitafederal.gov.br/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:`<input name="niContribuinte" onkeydown="window.keys=(window.keys||0)+1"><button onclick="document.querySelector('p').textContent='Não foi possível concluir a ação para o contribuinte informado. 106'">Emitir Certidão</button><p></p>`}));const page=await context.newPage();await page.goto('https://servicos.receitafederal.gov.br/form');const job={mode:'issue',status:'awaiting_user',cnpj:'00000000000191',context,portal:{allowedHosts:['servicos.receitafederal.gov.br']}};await advance(job);assert.ok(await page.evaluate(()=>window.keys>=14));const result=await advance(job);assert.equal(result.status,'awaiting_user');assert.match(result.message,/106/);}finally{await browser.close();}
});
