const crypto = require('node:crypto');
const { launchBrowser } = require('../automation/launch');
const escape = value => String(value ?? '—').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const eventsPt={company_lookup:'Cadastro consultado',pdf_uploaded:'PDF anexado',official_pdf_captured:'PDF capturado do portal',official_pdf_comparison:'Comparação de PDF com o portal',portal_opened:'Portal aberto',portal_evidence:'Evidências registradas',report_created:'Relatório emitido',municipal_portal_discovered:'Portal municipal descoberto',municipal_portal_registered:'Portal municipal cadastrado',automatic_issuance_attempt:'Tentativa automática de emissão',portal_cancelled:'Consulta cancelada'};
const methodsPt={upload:'Anexado pelo responsável',official_download:'Download capturado no portal',official_response:'PDF capturado na resposta do portal',official_print_view:'PDF da versão final de impressão do órgão',official_html_print:'Página preliminar do órgão (obter versão final)' };
const typesPt={negativa:'Negativa',positiva:'Positiva',positiva_efeitos_negativa:'Positiva com efeitos de negativa',regular_fgts:'Regularidade do FGTS',irregular:'Irregular',indeterminada:'Não identificada'};
const stamp = value => value ? new Date(value).toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' }) + ' (Brasília)' : '—';
function reportHtml(snapshot) {
  const { company, rows, id, generatedAt, actor, audit, events } = snapshot;
  return `<!doctype html><html lang="pt-BR"><meta charset="utf-8"><title>Relatório de conferência</title><style>
  @page{size:A4;margin:18mm 16mm 20mm}*{box-sizing:border-box}body{font:11px Arial,sans-serif;color:#172c40;line-height:1.5}h1{font-size:24px;margin:0}h2{font-size:15px;margin-top:24px}.eyebrow{color:#6b7787;letter-spacing:1.5px;font-size:10px}.head{border-bottom:3px solid #186b65;padding-bottom:16px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:18px 0}.label{color:#667085;font-size:10px}.notice{padding:12px;background:#fff5db;border-left:3px solid #b58116}.card{break-inside:avoid;border:1px solid #dce3e9;padding:14px;margin:12px 0}.card h3{margin:0 0 10px;font-size:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hash{font:9px monospace;word-break:break-all}.url{overflow-wrap:anywhere;color:#315b76}table{border-collapse:collapse;width:100%;font-size:10px}td,th{text-align:left;border-bottom:1px solid #dce3e9;padding:7px;vertical-align:top;overflow-wrap:anywhere}tr{break-inside:avoid}.muted{color:#667085}.evidence{font-size:10px;overflow-wrap:anywhere}</style>
  <div class="head"><div class="eyebrow">CENTRAL DE CERTIDÕES · CONTROLE DE PRESTADORAS</div><h1>Relatório de conferência documental</h1><div class="muted">Registro ${escape(id)}</div></div>
  <div class="meta"><div><div class="label">EMPRESA</div><strong>${escape(company.name)}</strong><br>CNPJ ${escape(company.cnpj)}</div><div><div class="label">JURISDIÇÃO</div>${escape(company.municipality)}/${escape(company.uf)}<br>IBGE ${escape(company.municipalityCode)}</div><div><div class="label">RELATÓRIO GERADO EM</div>${escape(stamp(generatedAt))}</div><div><div class="label">RESPONSÁVEL IDENTIFICADO NO SISTEMA</div>${escape(actor)}</div></div>
  <div class="notice"><strong>${rows.filter(r => r.portal.required).every(r => r.certificate?.assessment.ready) ? 'Documentos disponíveis, dentro da validade e com origem ou conferência registrada.' : 'Há pendências de conferência documental.'}</strong><br>Este relatório registra as verificações efetivamente realizadas. Não autoriza pagamento, não comprova a execução do serviço e não substitui a análise do responsável. Datas e horas são as do servidor; não constituem carimbo de tempo certificado.</div>
  <h2>Certidões e resultados</h2>${rows.map(({ portal: p, certificate: c }) => `<div class="card"><h3>${escape(p.name)}</h3>${!p.required ? `<p>${escape(p.note)}</p>` : !c ? '<strong>Documento ausente · conferência pendente</strong>' : `<div class="grid"><div><div class="label">RESULTADO DA CONFERÊNCIA</div><strong>${escape(c.assessment.label)}</strong></div><div><div class="label">DECLARAÇÃO EXTRAÍDA DO PDF</div>${escape(typesPt[c.parsed.classification]||c.parsed.classification)}</div><div><div class="label">NÚMERO / CÓDIGO</div>${escape(c.parsed.number)}</div><div><div class="label">VENCIMENTO EXTRAÍDO</div>${escape(c.parsed.expiresAt)}</div><div><div class="label">CNPJ NO DOCUMENTO</div>${c.parsed.cnpjMatches ? 'Compatível com a empresa' : 'Não confirmado'}</div><div><div class="label">INTEGRIDADE DO ARQUIVO</div>${c.integrity ? 'SHA-256 confere com o arquivo armazenado' : 'Falha de integridade'}</div><div><div class="label">RECEBIDO EM</div>${escape(stamp(c.uploadedAt))}</div><div><div class="label">CONFERÊNCIA OFICIAL EM</div>${escape(stamp(c.validation.checkedAt))}</div></div><p><span class="label">ORIGEM</span><br>${escape(methodsPt[c.provenance.method]||c.provenance.method)} <span class="url">${escape(c.provenance.url || 'Arquivo anexado por usuário')}</span></p><p><span class="label">SHA-256 DO PDF</span><br><span class="hash">${escape(c.file.sha256)}</span></p><p>${escape(c.officialCapture ? 'PDF obtido diretamente do órgão. Controle de origem, validade e integridade; sem exigência de consulta adicional de autenticação.' : c.validation.note || 'Autenticidade ainda não confirmada no portal emissor.')}</p>${c.validation.evidenceFile ? `<p class="hash">PDF de referência: ${escape(c.validation.evidenceFile.sha256)}</p>` : ''}${c.parsed.warnings.map(w => `<div>${escape(w)}</div>`).join('')}`}<p class="url">Portal selecionado: ${escape(p.url || 'Não cadastrado / não aplicável')}</p></div>`).join('')}
  <h2>Trilha de conferência</h2><p>Eventos vinculados a este CNPJ, preservados até a emissão do relatório. A indicação de abertura de portal ou captura de tela não equivale a uma resposta positiva de autenticidade.</p><table><thead><tr><th>Data/hora de Brasília</th><th>Evento</th><th>Responsável</th></tr></thead><tbody>${events.slice(0,60).map(e => `<tr><td>${escape(stamp(e.at))}</td><td>${escape(eventsPt[e.type]||e.type)}${typeof e.portal==='string' ? '<br>' + escape(e.portal) : ''}</td><td>${escape(e.actor)}</td></tr>`).join('')}</tbody></table>${events.length > 60 ? '<p>Lista resumida aos 60 eventos mais recentes. O comprovante JSON contém o registro completo.</p>' : ''}
  <h2>Evidências capturadas</h2>${events.filter(e => e.evidence?.length).map(e => e.evidence.map(v => `<div class="card evidence"><strong>${escape(stamp(v.capturedAt))}</strong><br><span class="url">${escape(v.url)}</span><br>Imagem SHA-256: <span class="hash">${escape(v.screenshot.sha256)}</span><br>Texto SHA-256: <span class="hash">${escape(v.pageText.sha256)}</span></div>`).join('')).join('') || '<p>Nenhuma captura de tela registrada nesta consulta.</p>'}
  <h2>Integridade e limites do registro</h2><p>Verificação da cadeia local de eventos: <strong>${audit.ok ? 'íntegra no momento da geração' : 'FALHOU'}</strong>. Eventos: ${audit.count}.</p><p class="hash">Cabeça da cadeia: ${escape(audit.head)}</p><p>Hashes e autenticação da trilha detectam alterações com a chave local preservada. Um administrador com acesso ao banco e à chave pode reconstruir registros. Para prova temporal externa, é necessária integração com carimbo de tempo confiável e armazenamento externo imutável.</p><p>Fonte cadastral: ${escape(company.source)}. Consultada em ${escape(stamp(company.fetchedAt))}.</p><p class="url">${escape(company.sourceUrl)}</p></html>`;
}
async function createReport({ company, rows, store, actor }) {
  const audit = store.checkAudit(); if (!audit.ok) throw new Error('Falha na integridade da trilha. Relatório bloqueado para investigação.');
  const snapshot = { id: crypto.randomUUID(), generatedAt: new Date().toISOString(), actor, company, rows, audit, events: store.events(company.cnpj) };
  const browser = await launchBrowser(true);
  let buffer;
  try { const page = await browser.newPage(); await page.setContent(reportHtml(snapshot), { waitUntil: 'load' }); buffer = await page.pdf({ format: 'A4', printBackground: true, displayHeaderFooter: true, headerTemplate: '<div></div>', footerTemplate: '<div style="font-size:9px;color:#687585;width:100%;text-align:center">Central de Certidões · Página <span class="pageNumber"></span> de <span class="totalPages"></span></div>', margin: { bottom: '20mm', top: '18mm', left: '16mm', right: '16mm' } }); } finally { await browser.close(); }
  const file = store.saveFile('reports', buffer, 'pdf'); const receipt = store.saveFile('reports', Buffer.from(JSON.stringify({ ...snapshot, pdf: file }, null, 2)), 'json');
  const report = { id: snapshot.id, cnpj: company.cnpj, generatedAt: snapshot.generatedAt, actor, file, receipt };
  store.put('report', report.id, report); store.audit({ type: 'report_created', cnpj: company.cnpj, reportId: report.id, file, receipt }, actor); return report;
}
module.exports = { reportHtml, createReport };
